### ISSUE TITLE
Notification & Privacy policy

### ISSUE THREAD

**Issue by sultannurlanov** [MyDataCoin/bridge-client#32]
1)Notification link not working
(Ссылка уведомления не работает)

![уведомление](https://user-images.githubusercontent.com/120353625/211574102-784af531-b2f7-4c58-83a9-360905b1af8e.png)

2)   by clicking on the privacy policy link. the page remains unchanged and 
the user does not understand if the page has been navigated 
(при нажатии на ссылку политика конфиденциальности. страница остается неизменной и пользователь 
не понимает перешла ли страница)
3) navigation bar not working on privacy policy page
(на странице политика конфиденциальности не работает панель навигации )
![navigation ](https://user-images.githubusercontent.com/120353625/211573748-34889fa8-a3f9-4190-9b44-d73720e9f010.png)

**Comment by asagynbaev** [comment]
#32 closes
